//
//  SKSymbol.swift
//  Generated by SFSymbolsEnumGenerator
//  Generated on 2025-08-05 11:20:50
//

import Foundation
import SwiftUI

// MARK: - SF Symbols
public struct SKSymbol: Codable, Sendable, Equatable, Hashable {
    public var rawValue: String
    public var categories: [SKSymbolCategory] = []
    public var words: [String] = []

    public static func == (lhs: SKSymbol, rhs: SKSymbol) -> Bool {
        lhs.rawValue == rhs.rawValue
    }

    public static func ~= (lhs: SKSymbol, rhs: SKSymbol) -> Bool {
        lhs.rawValue == rhs.rawValue
    }
}
