//
//  SKSymbol+Extensions.swift
//  Generated by SFSymbolsEnumGenerator
//  Generated on 2025-08-05 11:20:50
//

import Foundation
import SwiftUI

#if canImport(UIKit)
import UIKit
public typealias SFImage = UIImage
#elseif canImport(AppKit)
import AppKit
public typealias SFImage = NSImage
#endif

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
extension SKSymbol {
    public var swiftUIImage: Image {
        return Image(systemName: self.rawValue)
    }

    public var image: SFImage? {
        return SFImage(systemName: self.rawValue)
    }
}

extension SFImage {
    public convenience init?(symbol: SKSymbol, withConfiguration configuration: UIImage.Configuration?) {
        self.init(systemName: symbol.rawValue, withConfiguration: configuration)
    }

    public convenience init?(symbol: SKSymbol, compatibleWith traitCollection: UITraitCollection?) {
        self.init(systemName: symbol.rawValue, compatibleWith: traitCollection)
    }
}
