//
//  SKSymbols.swift
//  Generated by SFSymbolsEnumGenerator
//  Generated on 2025-08-05 11:20:50
//

import Foundation
import SwiftUI

// MARK: - SF Symbols Categories
public enum SKSymbolCategory: String, Codable, Sendable {
    case all = "all"
    case whatsnew = "whatsnew"
    case communication = "communication"
    case weather = "weather"
    case maps = "maps"
    case objectsandtools = "objectsandtools"
    case devices = "devices"
    case cameraandphotos = "cameraandphotos"
    case gaming = "gaming"
    case connectivity = "connectivity"
    case transportation = "transportation"
    case privacyandsecurity = "privacyandsecurity"
    case human = "human"
    case home = "home"
    case editing = "editing"
    case textformatting = "textformatting"
    case media = "media"
    case keyboard = "keyboard"
    case commerce = "commerce"
    case time = "time"
    case health = "health"
    case shapes = "shapes"
    case indices = "indices"
    case math = "math"
    case multicolor = "multicolor"
    case nature = "nature"
    case arrows = "arrows"
    case variablecolor = "variablecolor"
    case fitness = "fitness"
    case automotive = "automotive"
    case accessibility = "accessibility"
}

extension SKSymbolCategory {
    public var displayName: String {
        let key = "Symobl.Category." + self.rawValue
        return NSLocalizedString(key, bundle: .module, comment: rawValue)
    }

    public var icon: SKSymbol {
        switch self {
        case .all: return .squareGrid2X2
        case .whatsnew: return .sparkles
        case .multicolor:
            if #available(iOS 14.0, *) {
                return .paintpalette
            } else {
                return .pencilTip
            }
        case .variablecolor:
            if #available(iOS 16.0, *) {
                return .sliderHorizontalBelowSquareAndSquareFilled
            } else {
                return .pencilTipCropCircleBadgePlus
            }
        case .communication: return .message
        case .weather: return .cloudSun
        case .maps: return .map
        case .objectsandtools: return .folder
        case .devices: return .desktopcomputer
        case .cameraandphotos: return .camera
        case .gaming: return .gamecontroller
        case .connectivity: return .antennaRadiowavesLeftAndRight
        case .transportation: return .carFill
        case .automotive:
            if #available(iOS 16.1, *) {
                return .steeringwheel
            } else {
                return .carFill
            }
        case .accessibility:
            if #available(iOS 17.0, *) {
                return .accessibility
            } else {
                return .teletype
            }
        case .privacyandsecurity: return .lock
        case .human: return .personCropCircle
        case .home: return .house
        case .fitness:
            if #available(iOS 16.0, *) {
                return .figureRun
            } else {
                return .person
            }
        case .nature:
            if #available(iOS 14.0, *) {
                return .leaf
            } else {
                return .sunHaze
            }
        case .editing: return .sliderHorizontal3
        case .textformatting: return .textformat
        case .media: return .playpause
        case .keyboard: return .command
        case .commerce: return .cart
        case .time: return .timer
        case .health: return .heart
        case .shapes: return .squareOnCircle
        case .arrows:
            if #available(iOS 14.0, *) {
                return .arrowForward
            } else {
                return .arrowRight
            }
        case .indices: return .aCircle
        case .math: return .xSquareroot
        }
    }

    public var symbols: [SKSymbol] {
        return SKSymbol.allCases.filter { $0.categories.contains(self) }
    }
}

extension SKSymbolCategory {
    public static var allCases: [SKSymbolCategory] {
        return [
            .all,
            .whatsnew,
            .multicolor,
            .variablecolor,
            .communication,
            .weather,
            .maps,
            .objectsandtools,
            .devices,
            .cameraandphotos,
            .gaming,
            .connectivity,
            .transportation,
            .automotive,
            .accessibility,
            .privacyandsecurity,
            .human,
            .home,
            .fitness,
            .nature,
            .editing,
            .textformatting,
            .media,
            .keyboard,
            .commerce,
            .time,
            .health,
            .shapes,
            .arrows,
            .indices,
            .math
        ]
    }
}
